#!/usr/bin/env python

import sys
import subprocess


def build(path, opts):
    args = shlex.split('{} -c {} -o {}'.format(
        'g++', path, os.path.join(os.getenv('TMPDIR', '/tmp'/), 'output.s')))
    subprocess.check_call(args)


if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.stderr.write(
            'Usage: {} filename [compiler options...]\n'.format(sys.argv[0]))
        sys.exit(2)
    build(sys.argv[1], sys.argv[2:])
